image: 'docker:latest'
stages:
    - build
    - publish
before_script:
    - docker info
build:
    stage: build
    script:
        - echo $CI_COMMIT_TAG
        - 'docker build -t too-young:$CI_COMMIT_TAG .'
    tags:
        - HK1
publish:
    stage: publish
    script:
        - >-
            docker tag too-young:$CI_COMMIT_TAG
            zeekozhu/too-toung:$CI_COMMIT_TAG
        - 'docker tag too-young:$CI_COMMIT_TAG zeekozhu/too-toung:latest'
        - 'docker push zeekozhu/too-young:$CI_COMMIT_TAG'
        - 'docker push zeekozhu/too-young:latest'
    only:
        - tags
        - triggers
        - schedules
        - web
    tags:
        - HK1
