image: 'docker:latest'
stages:
    - build
    - publish
before_script:
    - docker info
build:
    stage: build
    script:
        - >-
            docker run -t --rm -v $(pwd):/app --workdir /app
            microsoft/aspnetcore-build sh -c 'ls && echo $(pwd) && cd
            TooYoung.Web && dotnet restore --configfile ../Nuget.Config &&
            dotnet publish -c Release -o ./bin/Release/PublishOutput'
        - >-
            docker run -t --rm -v $(pwd):/app --workdir /app
            microsoft/aspnetcore-build sh -c 'ls && echo $(pwd) && cd
            TooYoung.Web && dotnet restore --configfile ../Nuget.Config &&
            dotnet test'
    tags:
        - HK1
publish:
    stage: publish
    script:
        - cd ./TooYoung.Web
        - 'docker build -t too-young:$CI_COMMIT_TAG .'
        - >-
            docker tag too-young:$CI_COMMIT_TAG
            zeekozhu/too-toung:$CI_COMMIT_TAG
        - 'docker tag too-young:$CI_COMMIT_TAG zeekozhu/too-toung:latest'
        - 'docker push zeekozhu/too-young:$CI_COMMIT_TAG'
        - 'docker push zeekozhu/too-young:latest'
    only:
        - tags
        - triggers
        - schedules
        - web
    tags:
        - HK1
