image: 'docker:latest'
stages:
    - test
    - build
    - publish
before_script:
    - docker info
test:
    stage: test
    script:
        - 'docker build -t too-young:$CI_COMMIT_SHA .'
        - 'docker rmi too-young:$CI_COMMIT_SHA'
    tags:
        - HK1
    except:
        - tags
build:
    stage: build
    script:
        - 'docker build -t too-young:$CI_COMMIT_SHA .'
    tags:
        - HK1
    only:
        - tags
        - web
publish:
    stage: publish
    script:
        - docker login -u zeekozhu -p $CI_REGISTRY_PASSWORD
        - >-
            docker tag too-young:$CI_COMMIT_SHA
            zeekozhu/too-young:$CI_COMMIT_TAG
        - 'docker tag too-young:$CI_COMMIT_SHA zeekozhu/too-young:latest'
        - 'docker push zeekozhu/too-young:$CI_COMMIT_TAG'
        - 'docker push zeekozhu/too-young:latest'
        - 'docker rmi too-young:$CI_COMMIT_SHA'
    only:
        - tags
        - web
    tags:
        - HK1
